### Login with valid credentials 
POST http://127.0.0.1:3001/user/login HTTP/1.1
Content-Type: application/json

{ 
    "email": "mies2@gmail.com",
    "username":"user2", 
    "password":"mies" 
}

### Protected route test, for example profile
GET http://127.0.0.1:3001/user/profile HTTP/1.1
Content-Type: application/json
### Register
POST http://127.0.0.1:3001/auth/register HTTP/1.1
Content-Type: application/json

{ 
    "email": "mies3@gmail.com",
    "username":"user3", 
    "password":"mies" 
}
###
POST http://127.0.0.1:3001/mods/newMod HTTP/1.1
Content-Type: application/json

{ 
    "mod_name": "random Mod"
}

### GET mods that have categories
GET http://127.0.0.1:3001/categories/4 HTTP/1.1
Content-Type: application/json

### Add categories to mods
POST http://127.0.0.1:3001/categories/4 HTTP/1.1
Content-Type: application/json

{
    "category_name": "test category"
}

####
GET http://127.0.0.1:3001/wr-history/1 HTTP/1.1
Content-Type: application/json

### Add WR video to a category
POST http://127.0.0.1:3001/categories/2/wr-video HTTP/1.1
Content-Type: application/json

{
    "wr_video": "https://www.youtube.com/embed/m8M_BjRErmM"
}

### Check resource links
GET http://localhost:3001/mods/1/resourcelinks HTTP/1.1
Content-Type: application/json