### Login with valid credentials 
POST http://127.0.0.1:3001/user/login HTTP/1.1
Content-Type: application/json

{ 
    "email": "mies2@gmail.com",
    "username":"user2", 
    "password":"mies" 
}
### protected route, for example profile
GET http://127.0.0.1:3001/user/profile HTTP/1.1
Content-Type: application/json

### register
POST http://127.0.0.1:3001/auth/register HTTP/1.1
Content-Type: application/json

{ 
    "email": "mies3@gmail.com",
    "username":"user3", 
    "password":"mies" 
}

### GET mods that have categories

GET http://127.0.0.1:3001/mods/categories HTTP/1.1
Content-Type: application/json

### GET categories that a mod has

GET http://127.0.0.1:3001/mods/categories/1 HTTP/1.1
Content-Type: application/json