####
POST http://localhost:3001/mods/newmod HTTP/1.1
Content-Type: application/json

{ 
    "mod_name": "test-mod3"
}

####
POST http://localhost:3001/mods/2/categories HTTP/1.1
Content-Type: application/json

{ 
    "category_name": "test-category"
}